<?php

function admin_menu() {
    $items['greeting'] = array(
        'title' => 'Hello administrator',
        'page callback' => 'greet_admin',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK
    );

    return $items;
}

function admin_user_login(&$edit, $account) {
    $_GET['destination'] = 'greeting';
}

function greet_admin() {
    return '<p>You are an administrator.</p>';
}
